### ISSUE TITLE
S3 Put object forever signing

### ISSUE THREAD

**Issue by vibe0508** [awslabs/aws-sdk-swift#573] opened 2022-04-19 06:29 UTC
## Description
S3 Put object is being stuck when I try to upload a file. From stack trace, looks like SDK tries to sign whole request including file itself etc.

## Context
I'm trying to implement an application that uploads photos to S3. So main functionality is being blocked.

## Environment
* AWS Swift SDK version used: 0.1.x (tried every patch version with same result)
* Operating System and version (iOS/macOS/Linux): macOS
* Xcode version (if applicable): 13.2.1
* Swift compiler version (if applicable): 1300.0.47.5
* Swift Tools version (if applicable):
* I'm using SPM

## Reproduction Steps
1. Initiate S3Client with static credentials:2. 
```
let credConfig = AWSCredentialsProviderStaticConfig(
    accessKey: "",
    secret: "",
    sessionToken: nil,
    shutDownCallback: nil
)

let config = try S3Client.S3ClientConfiguration(
    credentialsProvider: AWSCredentialsProvider.fromStatic(credConfig),
    region: "eu-west-1"
)

let s3Client = S3Client(config: s3Config)
```

2. Start file upload to S3: 
```
let body = try ByteStream.from(data: Data(contentsOf: fileURL))

s3.putObject(
    input: PutObjectInput(
        body: body,
        bucket: bucketName,
        key: "\(folder)/\(filename)"
    ),
    completion: { [unowned self] result in
        // Handling result here
    }
)
```

## Observed Behavior
Application get's stuck with 99% processor load. Stack trace was to big to fit into the issue, so I [uploaded it as a file](https://drive.google.com/file/d/1Pbu2Buw2eTM7sMAd_8Wd40a2kM9CDW8K/view?usp=sharing).
## Expected Behavior
S3 PUT OBJECT request is sent within reasonable time.

## Possible Solution
As far as I know, it's not mandatory to include request body into request signing.

**Comment by tomharvey** [comment] 2022-04-21 22:09
Possible duplicate of https://github.com/awslabs/aws-sdk-swift/issues/531 which notes a fix in v0.2.1

**Comment by ganeshnj** [comment] 2022-11-03 16:33
https://github.com/awslabs/aws-sdk-swift/issues/531 is closed, @vibe0508 is this still an issue?

**Comment by ganeshnj** [comment] 2022-11-07 17:55
We must add support for configuring `unsignedBody` flag at client level to improve perf and CPU usage.

@vibe0508 could you share size of payload you are trying to upload?

**Comment by ganeshnj** [comment] 2022-12-21 18:39
I just tried to upload a 1GB file and it worked without any issues.

```swift
SDKLoggingSystem.initialize(logLevel: .debug)
let config = try await S3Client.S3ClientConfiguration()
let client = S3Client(config: config)
let fileURL = URL(fileURLWithPath: "/Users/jangirg/Desktop/LargeTestFile")
let data = try Data(contentsOf: fileURL)
let putObjectInput = PutObjectInput(body: ByteStream.from(data: data), bucket: "jangirg-s3-test", key: "LargeTestFile")
let putObjectOutput = try await client.putObject(input: putObjectInput)
print(putObjectOutput)
```

I'm going to close this ticket.

We have separate ticket on signing improvement
https://github.com/awslabs/aws-sdk-swift/issues/656
https://github.com/awslabs/aws-sdk-swift/issues/657

**Closed by ganeshnj** 2022-12-21 18:39 UTC
Labels: feature-request
