### ISSUE TITLE
Build failure M1 Mac

### ISSUE THREAD

**Issue by qiquanlu** [awslabs/aws-sdk-swift#867] opened 2023-02-07 14:14 UTC
### Describe the bug

Hi AWS team,

I'm having issue when building my app as soon as I added aws-sdk-swift in package manager

The module that XCode complaining is AwsChecksums, and error message is 

`Implicit declaration of function '__crc32cb' is invalid in C99`

This is a clean default XCode 14.1 app targeting IOS 16.0, by only adding aws-sdk-swift via package manager.

I'm following 

https://docs.aws.amazon.com/sdk-for-swift/latest/developer-guide/getting-started.html

"Adding the AWS SDK for Swift to an existing Xcode project" section

![Screenshot 2023-02-07 at 9 02 40 AM](https://user-images.githubusercontent.com/29985103/217266338-f368a97c-c83c-4378-93f3-73f250bbf789.png)

### Expected Behavior

app should compile and run

### Current Behavior

xcode complains crc32c_arm.c file from AwsChecksums

and reporting errors like

`Implicit declaration of function '__crc32cb' is invalid in C99`

see attached screenshot 

![Screenshot 2023-02-07 at 9 02 40 AM](https://user-images.githubusercontent.com/29985103/217267461-bca77119-974b-4812-ae0b-d97ea8550244.png)

### Reproduction Steps

XCode create a new IOS project, select IOS -> App

Run on an actual device -> success launched on device

Go to package manager add package dependency, https://github.com/awslabs/aws-sdk-swift.git

Run on an actual device -> Build failed with screenshot
![Screenshot 2023-02-07 at 9 02 40 AM](https://user-images.githubusercontent.com/29985103/217268291-974d1e04-96bc-46d4-b0c3-97168eca2471.png)

### AWS SWIFT SDK version used

0.9.1

### Compiler and Version used

swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)

### Operating System and version

macOS Ventura Version 13.0.1 (22A400)

**Comment by qiquanlu** [comment] 2023-02-08 13:46
after trying out with different versions, I found out the issue start from SDK v 0.9.0. I'm using 0.8.0 for now. Don't have an Intel mac to test, but the error comes from the arm related file, I assume this only affect mac silicon computer

**Comment by jbelkins** [comment] 2023-02-08 20:18
@qiquanlu Thanks for filing this issue.  We're going to try & reproduce it.  We will get back to you here if we need more info.

**Comment by jbelkins** [comment] 2023-02-08 21:30
@qiquanlu Was able to reproduce this build failure on macOS 13.2 / Xcode 14.2.

I created an iOS app project with default settings.  I added this SDK v0.9.1 to the project and to the iOS app target.
I connected an iOS device running iOS 16.2.

- When running Xcode on an Intel Mac: The test app compiled & ran successfully to a simulator and to a device.
- When running Xcode on an M1 Mac: The test app compiled & ran successfully when targeting the simulator, but failed to build as described above targeting a device.

We will investigate and determine a fix.

**Comment by jbelkins** [comment] 2023-02-09 21:39
@qiquanlu This issue has been fixed in AWS SDK for Swift version 0.9.2:
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.9.2

Please try this version with your iOS project and verify that the issue is fixed.

**Closed by jbelkins** 2023-02-09 21:39 UTC
Labels: bug, investigating, area/aws-client-runtime, area/aws-crt

**Comment by qiquanlu** [comment] 2023-02-10 12:50
@jbelkins Thanks! it works

> @qiquanlu This issue has been fixed in AWS SDK for Swift version 0.9.2: https://github.com/awslabs/aws-sdk-swift/releases/tag/0.9.2
> 
> Please try this version with your iOS project and verify that the issue is fixed.
