### ISSUE TITLE
IMDS Credentials Provider

### ISSUE THREAD

**Issue by epau** [awslabs/aws-sdk-swift#929] opened 2023-03-27 15:02 UTC
### Describe the feature

https://docs.aws.amazon.com/sdkref/latest/guide/feature-imds-credentials.html

~All SDKs seem to support this credential provider type and we should too. 

One thing to note, CRT already supports this and has a swift binding, so perhaps all we need to do is expose that.

### Use Case

N/A

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by smivij** [comment] 2023-12-06 20:52
Duplicate of #1094

**Closed as completed by smivij** 2023-12-06 20:52 UTC
Labels: feature-request
