### ISSUE TITLE
Connection timeout issue in URLSessionHTTPClient

### ISSUE THREAD

**Issue by sichanyoo** [awslabs/aws-sdk-swift#1457] opened 2024-04-24 13:52 UTC
Internal: /D123360092

**Comment by sichanyoo** [comment] 2024-04-26 16:52
Waiting for correspondence from customer.

**Comment by jbelkins** [comment] 2024-05-02 18:36
Unable to reproduce the customer's issue but a potential fix for this issue has been delivered to Amplify-swift in aws-sdk-swift 0.36.2.  Will follow up with affected customer & support engineer once this has been released by Amplify.

**Comment by jbelkins** [comment] 2024-05-03 01:05
Potential fix for this issue released in Amplify 2.33.2
https://github.com/aws-amplify/amplify-swift/releases/tag/2.33.2

**Comment by jbelkins** [comment] 2024-05-22 16:21
Released in AWS SDK for Swift 0.44.0
https://github.com/awslabs/aws-sdk-swift/releases/tag/0.44.0

**Closed by jbelkins** 2024-05-22 16:21 UTC
