### ISSUE TITLE
Extensible Credential Providers

### ISSUE THREAD

**Issue by kneekey23** [awslabs/aws-sdk-swift#352] opened 2021-08-20 21:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

See /seps/accepted/shared/extensible-creds.md
 May be provided by CRT

**Comment by ganeshnj** [comment] 2022-10-10 18:55
There is reference arch spec for creds providers which must be followed.

**Comment by smivij** [comment] 2023-02-07 01:14
Changed to priority 2 based on feature matrix

**Comment by epau** [comment] 2023-03-31 19:08
Most of the work is in CRT https://github.com/awslabs/aws-crt-swift/issues/177

**Comment by jbelkins** [comment] 2023-08-11 16:44
Duplicate of #1073

**Closed by jbelkins** 2023-08-11 16:44 UTC
