### ISSUE TITLE
posix_memalign failed to allocate memory when calling SDK with expired or missing credentials

### ISSUE THREAD

**Issue by shepazon** [awslabs/aws-sdk-swift#876] opened 2023-02-13 17:11 UTC
**Update:** After a couple of days of investigation, I've discovered the problem here is that both on my EC2 instance and my Docker instance, my AWS credentials have expired (the latter is using the creds from the underlying EC2 instance). If I refresh my credentials, this issue goes away.

### Describe the bug

This issue started happening on Friday (February 10, 2023). Before that, the same code was running fine. Upon building my DynamoDB example program, running it causes the error to occur when running the line:

```swift
ddbClient = try DynamoDBClient(region: "us-east-2")
```

**This is also happening when I try to create an `IAMClient` object.**

I have a minimized test case below.

### Expected Behavior

The code should throw an appropriate exception.

### Current Behavior

Upon running the program, this line causes the following output to occur:

```
posix_memalign failed to allocate memoryAborted (core dumped)
```

This is happening on both 0.9.0 and 0.9.2. I had noticed the problem starting around the time 0.9.2 was released, so I tried setting my package to build with 0.9.0 specifically but the issue still occurs.

### Reproduction Steps

Use this as the main program, build and run:

```swift
import Foundation
import ClientRuntime
import AWSClientRuntime
import AWSDynamoDB

@main
public struct repro {

    public static func main() async {
	print("Begin")
	do {
        	let client = try DynamoDBClient(region: "us-east-2")
	} catch {
		dump(error)
	}
        print("Got client")
    }
}
```

### AWS SWIFT SDK version used

0.9.2

### Compiler and Version used

Swift 5.7.3

### Operating System and version

Ubuntu 22.04

**Comment by shepazon** [comment] 2023-02-13 19:01
This is happening when I try to instantiate an IAMClient object as well. This seems to be a broader issue than I thought.

**Comment by ganeshnj** [comment] 2023-02-13 23:02
There is definitely something else missing from your setup which isn't clear

We did testing on AL2 (out most Linux customers are on i.e. Lambda) and Ubuntu with the same code snippet and it worked fine.

For ubuntu
```
docker pull swift:jammy
docker run -it swift:jammy bash
```
Create test app
```
mkdir TestSdk
cd TestSdk
swift package init --type executable
```
Update Package.swift
```swift
// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "TestSdk",
    platforms: [.macOS(.v10_15), .iOS(.v13)],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/awslabs/aws-sdk-swift", from: "0.9.2"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .executableTarget(
            name: "TestSdk",
            dependencies: [
                .product(name: "AWSDynamoDB", package: "aws-sdk-swift")
            ]),
        .testTarget(
            name: "TestSdkTests",
            dependencies: ["TestSdk"]),
    ]
)
```
Update TestSdk.swift
```swift
import AWSDynamoDB

@main
public struct TestSdk {
    public private(set) var text = "Hello, World!"

    public static func main() {
        print("Begin")
        do {
            let client = try DynamoDBClient(region: "us-east-2")
        } catch {
            dump(error)
        }
        print("Got client")
    }
}
```
finally 
```
swift build
swift run
```

Output
```
[771/771] Linking TestSdk
Build complete! (35.32s)
root@1e5daf4329ec:/home/TestSdk# swift run
Building for debugging...
Build complete! (0.31s)
Begin
Got client
root@1e5daf4329ec:/home/TestSdk#
```

Although, we had to install openssl in order it work which is a requirement anyway
```
apt update 
apt-get install libssl-dev
```

**Comment by ganeshnj** [comment] 2023-02-13 23:06
For AL2, 
```
yum install -y openssl-devel
```

**Comment by shepazon** [comment] 2023-02-14 15:27
Hm. This is strange. Because why would it stop working in an environment where it had been working earlier that same day?

**Comment by shepazon** [comment] 2023-02-14 21:06
So -- turns out this is happening because my AWS credentials expired. I don't understand why the SDK is crashing with an error like this instead of throwing an exception to me though.

**Comment by jbelkins** [comment] 2023-02-14 22:31
@shepazon Thanks for the update, glad you figured out the reason for your crash, and you are correct to expect a relevant error message in this case.

**Comment by ganeshnj** [comment] 2023-02-20 18:17
Next step: we must be able reproduce this and create an action item to CRT team to throw a better message that tells about the expired credentials than a memory issue.

**Comment by smivij** [comment] 2023-10-13 19:22
Created below issue in CRT
https://github.com/awslabs/aws-crt-swift/issues/202

**Comment by dayaffe** [comment] 2023-10-23 18:24
This bug could not be reproduced using the latest versions of Swift SDK and its dependencies on Swift 5.7 / AL2 docker image. Spoke with @shepazon offline and we are aligned on closing this ticket.

**Closed by dayaffe** 2023-10-23 18:24 UTC
Labels: bug, oncall
