### ISSUE TITLE
End-to-end testing plan for credential providers

### ISSUE THREAD

**Issue by jbelkins** [awslabs/aws-sdk-swift#1041] opened 2023-06-14 18:50 UTC
Develop a plan for testing every credential provider end-to-end to ensure that they work as expected.

Automate the credential provider tests, and schedule them on CI along with other end-to-end / integration tests.

(Going forward, as credential providers are added, they should have end-to-end tests added as well)

**Comment by smivij** [comment] 2023-06-14 19:44
Closing as duplicate of #1040

**Closed** 2023-06-14 19:45 UTC
Labels: needs-triage
