### ISSUE TITLE
Incorrect encoding of iot topics

### ISSUE THREAD

**Issue by johndrewery** [awslabs/aws-sdk-swift#1101] opened 2023-09-02 00:40 UTC
### Describe the bug

In IoTDataPlaneClient, functions accepting a topic name convert forward slash within the project name to %2F.  e.g. my/topic/here becomes my%2Ftopic%2Fhere.  Topics should be able to contain '/'

### Expected Behavior

Topics should be appended to the URL for an MQTT operation with the slashes intact

### Current Behavior

Slashes are percent encoded

### Reproduction Steps

[urlTest.swiftpm.zip](https://github.com/awslabs/aws-sdk-swift/files/12502106/urlTest.swiftpm.zip)

### Possible Solution

In AWSIoTDataPlane/models/Models.swift:

extension PublishInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        guard let topic = topic else {
            return nil
        }
        return "/topics/\(topic.urlPercentEncoding())"
    }
}

This is wrong - urlPercentEncoding() causes the problem statement by percent encoding '/'

### AWS SWIFT SDK version used

main

### Compiler and Version used

14.2

### Operating System and version

MacOS 12.6.8 compiling for iOS >15

**Comment by jbelkins** [comment] 2023-09-05 22:05
@johndrewery By the Smithy definition of the publish operation for AWS IOT Data Plane, the `topic` component of the URL path is "non-greedy" and forward slashes in the topic should indeed be encoded.
- Model: https://github.com/awslabs/aws-sdk-swift/blob/93a2e5bb2553e96a0f78e8fee312c47841ed9af9/codegen/sdk-codegen/aws-models/iot-data-plane.2015-05-28.json#L1851
- Smithy `httpLabel` trait docs (see "`httpLabel` serialization rules"):
https://smithy.io/2.0/spec/http-bindings.html#httplabel-trait

Further, the following code runs successfully with the SDK as-is, printing "Success" after an API call directed to `/topics/my%2Ftopic%2Fhere`:
```swift
import AWSIoTDataPlane

let client = try IoTDataPlaneClient(region: "us-east-1")
let input = PublishInput(topic: "my/topic/here")
do {
    _ = try await client.publish(input: input)
    print("Success")
} catch {
    print("Error: \(error.localizedDescription)")
}
```

Perhaps the cause of your problem is something different.  If you give me sample code for your API request and the console output for any error that might be returned, I can help you further, else I will close this issue.

**Comment by johndrewery** [comment] 2023-09-05 22:28
I don’t deny that example will work.  However it will publish to the topic /topics/my%2Ftopic%2Fherenot/topics/my/topic/hereas can be confirmed using the MQTT test client.  This is not desired behavior and my problem statement should perhaps have related more closely to this undesirable behavior.Thanks for the links, I will check them out.John Drewery On Sep 5, 2023, at 15:05, Josh Elkins ***@***.***> wrote:﻿
@johndrewery By the Smithy definition of the publish operation for AWS IOT Data Plane, the topic component of the URL path is "non-greedy" and forward slashes in the topic should indeed be encoded.

Model: https://github.com/awslabs/aws-sdk-swift/blob/93a2e5bb2553e96a0f78e8fee312c47841ed9af9/codegen/sdk-codegen/aws-models/iot-data-plane.2015-05-28.json#L1851
Smithy httpLabel trait docs (see "httpLabel serialization rules"):
https://smithy.io/2.0/spec/http-bindings.html#httplabel-trait

Further, the following code runs successfully with the SDK as-is, printing "Success" after an API call directed to /topics/my%2Ftopic%2Fhere:
import AWSIoTDataPlane

let client = try IoTDataPlaneClient(region: "us-east-1")
let input = PublishInput(topic: "my/topic/here")
do {
    _ = try await client.publish(input: input)
    print("Success")
} catch {
    print("Error: \(error.localizedDescription)")
}
Perhaps the cause of your problem is something different.  If you give me sample code for your API request and the console output for any error that might be returned, I can help you further, else I will close this issue.

**Comment by jbelkins** [comment] 2023-09-27 20:33
The sample code above publishes to "my/topic/here" and not to "my%2Ftopic%2Fhere"... I subscribed to both of those topics and my message was received on the first topic and not on the second.

Closing this issue; as far as can be determined, MQTT publish operation behaves as expected.

**Closed by jbelkins** 2023-09-27 20:33 UTC
Labels: bug
